#!/bin/bash
# Auto suspend and wake-up script
#
# Puts the computer on standby and automatically wakes it up at specified time
#
# Written by Romke van der Meulen <redge.online@gmail.com>
# Minor mods fossfreedom for AskUbuntu
# Additional modifications by k3can to improve clarity and reliability
#
# Takes a 24hour time HH:MM as its argument
# Example:
# suspend_until 9:30
# suspend_until 18:45

# Set suspend type.
# See "man rtcwake" for possible options.
SUSPEND_TYPE="mem"

if [ $# -lt 1 ]; then
    echo "Usage: suspend_until HH:MM"
    exit
fi

# Check whether specified time today or tomorrow
DESIRED=$((`date +%s -d "$1"`))
NOW=$((`date +%s`))
if [ $DESIRED -lt $NOW ]; then
    DESIRED=$((`date +%s -d "$1"` + 24*60*60))
fi

# Feedback
echo "Suspending until $1"

# Suspend system
rtcwake -l -m $SUSPEND_TYPE -t $DESIRED


# Any commands you want to launch after wakeup can be placed here
# 
# Example: 
# xset dpms force on
# ... To wake up with monitor enabled or change to "off" to force monitors disabled on wake.

echo "Wake up, Neo... The time is $(date '+%H:%M')"
